const fs = require('fs');
const path = require('path');
var program = require('commander');

program
  .version('0.0.1')
  .description('This tool can evaluate a directory of JSON files generated by ABAP report OFFLINE_SIMULATE_OCM_SYNC. This tool will verify existence of NodeID and ParentNodeID as well as uniqueness of NodeID per UICFilePath+ListPath.')
  .option('-d, --directory [path]', 'specify the relative or absolute [path] which contains the JSON files to be checked')
  .option('-n, --nodeId [nodeId]', '[nodeId] of records to be found')
  .parse(process.argv);

if (program.directory) {
  if (program.nodeId) {
    var sSearchForNodeId = program.nodeId;
  }
	  var sDirectoryPath = program.directory;
    var mVerify = {};
    var iProcessedFiles = 0;
    var iTotalErrors = 0;
    var oRecordFoundBySearchNodeId = null;

    fs.readdir(sDirectoryPath, function (err, files) {
        if (err) {
            throw new Error(err);
        }
        files.forEach(function (sFileName) {
            var sFilePath = path.join(sDirectoryPath, sFileName);
            var stat = fs.statSync(sFilePath);
            if (stat.isFile()) {
                var oJsonContent = JSON.parse(fs.readFileSync(sFilePath, 'utf8'));
                var aData = oJsonContent['Data'];
                var bErrorFound = false;
                if (aData && aData.length > 0) {
                    var sUICFilePath = oJsonContent.UICFilePath;
                    var sListPath = oJsonContent.ListPath;
                    var sUICFilePathListPath = sUICFilePath + sListPath;
                    if (mVerify[sUICFilePathListPath] === undefined) {
                        mVerify[sUICFilePathListPath] = {};
                    }
                    for (var i = 0; i < aData.length; i++) {
                        var oRecord = aData[i];
                        var sNodeID = undefined;
                        if (oRecord.hasOwnProperty('NodeID') === false) {
                            console.log('ERROR: file ' + sFileName);
                            console.log('ERROR: Missing Node ID');
                            console.log(oRecord);
                            iTotalErrors++;
                            bErrorFound = true;
                        } else {
                            sNodeID = oRecord['NodeID'];
                            if (sNodeID === null || sNodeID === '') {
                                console.log('ERROR: file ' + sFileName);
                                console.log('ERROR: Node ID is empty');
                                console.log(oRecord);
                                iTotalErrors++;
                                bErrorFound = true;
                            } else {
                                var mInstances = mVerify[sUICFilePathListPath];
                                if (mInstances[sNodeID] === sNodeID) {
                                    console.log('ERROR: file ' + sFileName);
                                    console.log('ERROR: duplicate Node ID');
                                    console.log(oRecord);
                                    iTotalErrors++;
                                    bErrorFound = true;
                                } else {
                                  if (sSearchForNodeId) {
                                    if (sSearchForNodeId === sNodeID) {
                                      oRecordFoundBySearchNodeId = oRecord;
                                    }
                                  }
                                    mInstances[sNodeID] = sNodeID;
                                }

                            };
                        };
                        if (oRecord.hasOwnProperty('ParentNodeID') === false) {
                            console.log('ERROR: file ' + sFileName);
                            console.log('ERROR: Missing ParentNodeID');
                            console.log(oRecord);
                            iTotalErrors++;
                            bErrorFound = true;
                        } else {
                            if (oRecord['ParentNodeID'] === null || oRecord['ParentNodeID'] === '') {
                                console.log('ERROR: file ' + sFileName);
                                console.log('ERROR: ParentNodeID is empty');
                                console.log(oRecord);
                                iTotalErrors++;
                                bErrorFound = true;
                            };
                        }
                    }
                }
                if (bErrorFound === false) {
                    console.log('No errors found for file ' + sFileName);
                }
                iProcessedFiles++;
            } else {
                console.log(sFileName + ' is not a file');
            }
        });
        console.log('TOTAL: ' + iProcessedFiles + ' files processed');
        console.log('TOTAL: ' + iTotalErrors + ' errors found');
        if (sSearchForNodeId) {
          if (oRecordFoundBySearchNodeId) {
            console.log('INFO: hit for requested node id: ' + sSearchForNodeId);
            console.log(oRecordFoundBySearchNodeId);
          } else {
            console.log('ERROR: no hit for requested node id: ' + sSearchForNodeId);
          }
        }
    });
} else {
  program.help();
}
